name: Auth
version: '${project.version}'
main: br.com.rabbithole.auth.Auth
api-version: 1.19
authors: [ FelipeSz_19 ]
description: Auth Provider for Rabbit Hole
depend:
  - Permissions
commands:
  register:
    description: Register Players in System
    aliases: [registrar]
  login:
    description: Auth Player in System
    aliases: [logar]
  changepassword:
    description: Update Player Password
    aliases: [trocarsenha]
